//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor 6.2.1.
// updater_res.rc

#define LAUNCHER_DLG 101
#define ID_PROGRESS_BAR 1001
#define ID_STATUS_LABEL 1002
